[sqlite3]
  dbname = "./test.db"

[mysql]
  dbname  = "sqlcomposer_api_test"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = "123123"
  sslmode = "false"
  blacklist = ["migrations"]